jonas-l-b/vwi_studienfuehrer

- index.php
- orderComments_submit.php
> Issue 9 gefixed

- header.php
- nav.php
- res/css/autocomplete.css
- res/lib/jquery.autocomplete.js
- search-autocomplete-api.php
Implementiert eine ziemlich gut funktionierende Suchfunktion auf Basis von autocomplete. Mittels Enter-Taste navigiert man sofort zum Ziel. Hat noch kleinere Bugs, funktioniert aber insgesamt sehr gut. Maustasteninput ist noch nicht gut vorhanden. Es gibt keine Result-Page wenn nichts gematched werden konnte, das ist eventuell auch noch verbesserungswürdig. 
Auf langfristige Sicht serverseitig eventuell zu hoher Aufwand für Datenbank. Extrahierung notwendiger Informationen in Arrays oder JSON-Files wäre eine Option, sollte das im Betrieb ein Problem darstellen.
> Search with autocomplete

- res/css/autocomplete.css
Damit man besser sieht, wohin man klicken soll
> change cursors

- inc/Autoloader.php
- inc/services/DatenbankService.php
- inc/services/SessionService.php
- inc/services/UserService.php
> Selbe Thematik --> selber branch

- admin_editInstitute.php
- admin_editLecturer.php
- admin_editModule.php
- admin_editSubject.php
- tree.php
> fix #20 und schafft Link-Teilbarkeit

- res/css/index.css
Ändert Design auf Veranstaltungsseite, falls noch keine Ratings vorhanden.
> neues Design Box

- index.php
Wie wäre es damit? Wenn ja können wir auch das Modal vereinfachen.
> Show button, but disabled

- connect.php
- index.php
Sieht echt übel aus im Change-Log, aber ich habe wirklich nur ein paar php-Zeilen rausgenommen und die Einrückung berichtigt.
Habe aus Versehen auch die connect.php-Änderung gepusht; macht das was aus, wenn die so im repository liegt? Wäre für mich einfacher :)
> Remove nun unnötige modal schleife

- database/studienfuehrer.sql
Mit einer Datenbankänderung geht es. Der Datensatz bleibt konsistent, dem Nutzer wird aber gegenbenenfalls bis Neuladen etwas falsches dargestellt.
> datenbankänderung fix #52

- database/studienfuehrer.sql
- index.php
Habs auf 2500 Zeichen reduziert, das ist auch schon ne ganze Menge. Serverseitig akzeptiert die db einfach nicht mehr; ich denke, das würde dann einfach abgeschnitten werden, sollte wirklich jemand JS umgehen.
> Restrict comment length

- admin.php
- admin_addAdmin_submit.php
- admin_addSuperAdmin_submit.php
- admin_admin_delete.php
- admin_superadmin_delete_submit.php
- database/studienfuehrer.sql
- inc/nav.php
- index.php
- res/css/admin.css
Führt Super-Administratoren ein, die Admin- und Super-Admin-Rechte verwalten können.
> Admin-Rechte verwalten

- delete-user-api.php
- header.php
- login.php
- res/js/script.js
- templates/deleteModal.template.html
- userProfile.php
Ein Nutzer kann sein Profil nun löschen. Hierbei hat er die Möglichkeit seine vorhandenen Bewertungen entweder anonymisiert zurückzulassen, oder diese ebenfalls zu löschen. 
Daten in Messages bleiben erhalten. "answer-required" wird aber auf 0 gesetzt. Dem Nutzer wird dies mitgeteilt.
Known issues:
- in der tabelle commentratings bleiben möglicherweise "tote daten" übrig (die aber nicht mehr zum nutzer gehören)
> Profil löschen

- register.php
unschön, betrifft ja aber nur leute, die absichtlich das javascript austricken also schön muss eigentlich nicht
> gimmicky fix #1 serverseitig

- index.php
- loadComments.php
> Kommentare werden mit ajax sortiert (sieht sauberer aus)

- tree.php
- tree_createTable.php
Passt die Suchfunktion dem neuen Ratingkonzept an. Müsste soweit eigentlich funktionieren. Up for discussion: schriftlich und mündlich beim Filtern zusammenfassen?
Falls du keine großen Fehler findest, können wir es wohl zumindest in new-rating-concept mergen.
> Ergebnistabelle

- login.php
Funktioniert unter localhost; auf Server (noch) nicht getestet!
> Redirect zur eigentlichen Seite (remember me)

- login.php
- module.php
Fügt Gesamtbewertung zur Modul-Seite hinzu. Letztes commit ist ein Start für ein interessantes Design, wobei ich wieder Probleme mit der Positionierung des Kreises habe ;)
Man könnte theoretisch den letzten commit löschen und mergen.
> Enhance module

- admin_createSubject.php
- admin_editSubject.php
- database/studienfuehrer.sql
- index.php
Du hattest doch gesagt, dass sich die LV-Nummer sowieso jedes Jahr ändern, richtig? Dieser Merge schmeißt die LV-Nummer raus. (Veranstaltungen eintragen und ändern ist getestet)
> Lv nummer löschen

- admin_createInstitute_submit.php
- admin_createModule_submit.php
- admin_createSubject.php
Führt strengere Datenprüfung bei Datenbankeintragung ein (hauptsächlich wurde aus UNDs ODERs). Außerdem beschreibt jetzt ein Hinweis in createSubject, was genau geprüft wird.
> Strengere Prüfung und Hinweis

- search.php
- tree.php
Um die Startseite besser nutzen zu können (nutzerspezifische Informationen, Neuheuten etc., damit Nutzer schön in den Studi hineingezogen werden), wurde die Veranstaltungssuche auf eine eigene Seite verschoben. Eine Referenz ist natürlich auf der Startseite erhalten geblieben.
Bei der Gelegenheit wurde außerdem die Startseite ein bisschen auf das wesentliche Reduziert (Wegfall unnötiger Überschriften etc).
> neuer Feed auf Startseite, Verschiebung Suche

- about.php
- login.php
-fehlt: auf register.php
-in db
> include guidelines

- inc/services/EmailService.php
- index.php
- loadComments.php
- sendMessage.php
- sendMessage_submit.php
- tree.php
- userProfile.php
Allows users to send messages to others
> Send message
